export const ROUTES = {
  HOME: '/',
  PITRU_MOKSHA_GAYA: '/pitru-moksha-gaya',
  PITRU_MOKSHA_GAYA_ONLINE: '/pitru-moksha-gaya/online',
  PITRU_MOKSHA_GAYA_OFFLINE: '/pitru-moksha-gaya/offline',
  RITUAL_SERVICES: '/ritual-services',
  RITUAL_SERVICES_ONLINE: '/ritual-services/online',
  RITUAL_SERVICES_OFFLINE: '/ritual-services/offline',
  TRAVEL_ASSISTANCE: '/travel-assistance',
  VAHI_RECORDS: '/vahi-records',
  RELIGIOUS_PARTNERS: '/religious-partners',
  KNOWLEDGE_CENTER: '/knowledge-center',
  ASK_GENZ_AI: '/zen-g',
  BOOKING: '/services',
  INQUIRY: '/contact',
  TRACKING: '/tracking',
  COMPLAINT: '/complaint',
  GRIEVANCE: '/grievance',
  FOUNDER_SUPPORT: '/founder-support',
  PRIVACY_POLICY: '/privacy-policy',
  BOOKING_TERMS: '/booking-terms',
  CANCELLATION_POLICY: '/cancellation-policy',
  /** @deprecated Prefer PRIVACY_POLICY */
  POLICIES_LEGAL_TERMS: '/privacy-policy',
  /** @deprecated Prefer CANCELLATION_POLICY; kept as alias for redirects/callers */
  REFUND_POLICY: '/cancellation-policy',
  /** @deprecated Prefer BOOKING_TERMS */
  TERMS: '/booking-terms',
  LOGIN: '/login',
  ACCOUNT: '/account',
  ACCOUNT_SERVICE_REQUESTS: '/account/service-requests',
  ACCOUNT_REGISTRATIONS: '/account/registrations',
  ACCOUNT_PROFILE: '/account/profile',
  DASHBOARD: '/dashboard',
  WHATSAPP: '/contact?channel=whatsapp',
  SERVICE_JOURNEY_QUOTATION: '/service-journey/quotation-agreement',
  SERVICE_JOURNEY_PAYMENT: '/service-journey/payment-confirmation',
  SERVICE_JOURNEY_FULFILMENT: '/service-journey/fulfilment-closure',
  TRACK_REGISTRATION: '/tracking?type=partner',
  TRACK_TRAVEL_COMPANION_REGISTRATION: '/tracking?type=companion',
  TRAVEL_COMPANION_REGISTER: '/travel-assistance/companion-register',
} as const;

export type RouteKey = keyof typeof ROUTES;
